# Generated by Django 5.1.4 on 2025-09-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrucksImportadosExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('identificacao', models.CharField(blank=True, max_length=30, null=True)),
                ('distpecorrido', models.CharField(blank=True, db_column='distPecorrido', max_length=20, null=True)),
                ('tempopadrao', models.CharField(blank=True, db_column='tempoPadrao', max_length=20, null=True)),
                ('velocidademedia', models.CharField(blank=True, db_column='velocidadeMedia', max_length=20, null=True)),
                ('tempomovimento', models.CharField(blank=True, db_column='tempoMovimento', max_length=20, null=True)),
                ('datahora', models.DateTimeField(blank=True, db_column='dataHora', null=True)),
                ('localizacao', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('velocidade', models.IntegerField(blank=True, null=True)),
                ('km', models.CharField(blank=True, max_length=5, null=True)),
                ('parado', models.CharField(blank=True, max_length=10, null=True)),
                ('tipomsg', models.CharField(blank=True, db_column='tipoMsg', max_length=30, null=True)),
                ('log', models.CharField(blank=True, max_length=10, null=True)),
                ('modo_emergencia', models.CharField(blank=True, db_column='modo_Emergencia', max_length=30, null=True)),
                ('bateria', models.IntegerField(blank=True, null=True)),
                ('dtimport', models.DateTimeField(blank=True, db_column='dtImport', null=True)),
                ('arquivo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_proximo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trucks_ImportadosExcel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrucksPosicaoCarroApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.BigIntegerField(blank=True, db_column='mId', null=True)),
                ('veiid', models.IntegerField(blank=True, db_column='veiID', null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=10, null=True)),
                ('lon', models.CharField(blank=True, max_length=10, null=True)),
                ('mun', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('rod', models.CharField(blank=True, max_length=50, null=True)),
                ('rua', models.CharField(blank=True, max_length=50, null=True)),
                ('vel', models.IntegerField(blank=True, null=True)),
                ('ori', models.IntegerField(blank=True, null=True)),
                ('tpmsg', models.IntegerField(blank=True, db_column='tpMsg', null=True)),
                ('dtinc', models.DateTimeField(blank=True, db_column='dtInc', null=True)),
                ('evtg', models.IntegerField(blank=True, db_column='evtG', null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('odm', models.IntegerField(blank=True, null=True)),
                ('lt', models.IntegerField(blank=True, null=True)),
                ('mlog', models.CharField(blank=True, db_column='mLog', max_length=10, null=True)),
                ('pcnome', models.CharField(blank=True, db_column='pcNome', max_length=50, null=True)),
                ('mot', models.CharField(blank=True, max_length=50, null=True)),
                ('motid', models.IntegerField(blank=True, db_column='motID', null=True)),
                ('prnome', models.CharField(blank=True, db_column='prNome', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('dtimport', models.DateTimeField(blank=True, db_column='dtImport', null=True)),
            ],
            options={
                'db_table': 'trucks_posicaoCarroAPI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrucksResumoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('diasemana', models.CharField(blank=True, db_column='diaSemana', max_length=20, null=True)),
                ('ligadoparado', models.CharField(blank=True, db_column='ligadoParado', max_length=8, null=True)),
                ('veimovi', models.CharField(blank=True, db_column='veiMovi', max_length=8, null=True)),
                ('iniciojornada', models.CharField(blank=True, db_column='InicioJornada', max_length=8, null=True)),
                ('fimjornada', models.CharField(blank=True, db_column='FimJornada', max_length=8, null=True)),
                ('jornada', models.CharField(blank=True, db_column='Jornada', max_length=8, null=True)),
                ('temponoturno', models.CharField(blank=True, db_column='tempoNoturno', max_length=20, null=True)),
                ('temponoturnoextra', models.CharField(blank=True, db_column='tempoNoturnoExtra', max_length=20, null=True)),
                ('estourojornada', models.CharField(blank=True, db_column='estouroJornada', max_length=20, null=True)),
                ('horaalmoco', models.CharField(blank=True, db_column='horaAlmoco', max_length=20, null=True)),
                ('tempoespera', models.CharField(blank=True, db_column='tempoEspera', max_length=20, null=True)),
                ('tempodescanso', models.CharField(blank=True, db_column='tempoDescanso', max_length=20, null=True)),
                ('tempodiurno', models.CharField(blank=True, db_column='tempoDiurno', max_length=20, null=True)),
                ('tempoextra', models.CharField(blank=True, db_column='TempoExtra', max_length=20, null=True)),
                ('dtalteracao', models.CharField(blank=True, db_column='dtAlteracao', max_length=10, null=True)),
                ('useralteracao', models.CharField(blank=True, db_column='userAlteracao', max_length=50, null=True)),
            ],
            options={
                'db_table': 'trucks_ResumoDiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrucksVeiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veiid', models.IntegerField(blank=True, db_column='veiID', null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('vs', models.FloatField(blank=True, null=True)),
                ('tcmd', models.IntegerField(blank=True, db_column='tCmd', null=True)),
                ('tmac', models.CharField(blank=True, db_column='tMac', max_length=20, null=True)),
                ('ecmd', models.CharField(blank=True, db_column='eCmd', max_length=20, null=True)),
                ('tp', models.IntegerField(blank=True, null=True)),
                ('ta', models.IntegerField(blank=True, null=True)),
                ('eqp', models.IntegerField(blank=True, null=True)),
                ('mot', models.CharField(blank=True, max_length=150, null=True)),
                ('prop', models.CharField(blank=True, max_length=20, null=True)),
                ('die', models.CharField(blank=True, db_column='dIE', max_length=20, null=True)),
                ('loc', models.CharField(blank=True, max_length=20, null=True)),
                ('ident', models.CharField(blank=True, max_length=50, null=True)),
                ('vmanut', models.IntegerField(blank=True, db_column='vManut', null=True)),
            ],
            options={
                'db_table': 'trucks_veiculos',
                'managed': False,
            },
        ),
    ]
