# Generated by Django 5.1.4 on 2025-08-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cnpjcpf', models.CharField(blank=True, max_length=14, null=True)),
                ('nm_agregado', models.CharField(max_length=150)),
                ('dt_atualizacao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'agregado',
                'verbose_name_plural': 'agregados',
                'db_table': 'ope_agregado',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('cd_sistema', models.IntegerField(blank=True, null=True)),
                ('nm_sistema', models.CharField(blank=True, max_length=150, null=True)),
                ('cd_grupo', models.IntegerField(blank=True, null=True)),
                ('nm_grupo', models.CharField(blank=True, max_length=150, null=True)),
                ('rf_item', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_item', models.CharField(max_length=150)),
                ('unidade', models.CharField(max_length=10)),
                ('vl_frota', models.FloatField(blank=True, null=True)),
                ('vl_sistema', models.FloatField(blank=True, null=True)),
                ('percentual', models.FloatField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'db_table': 'ope_item',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tipo_servico', models.IntegerField(blank=True, null=True)),
                ('nm_tipo_servico', models.CharField(blank=True, max_length=150, null=True)),
                ('cd_servico', models.IntegerField()),
                ('nm_servico', models.CharField(max_length=255)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'db_table': 'ope_servico',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('cd_veiculo', models.IntegerField()),
                ('cd_frota', models.IntegerField()),
                ('nm_frota', models.CharField(max_length=150)),
                ('cd_centro_custo', models.IntegerField()),
                ('nm_centro_custo', models.CharField(max_length=150)),
                ('cnpjcpf', models.CharField(blank=True, max_length=14, null=True)),
                ('dt_inativacao', models.DateField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField()),
                ('placa', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_placa', to='operacional.agregado')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'db_table': 'ope_veiculo',
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_abastecimento', models.IntegerField()),
                ('dt_abastecimento', models.DateTimeField(blank=True, null=True)),
                ('cd_ponto_apoio', models.IntegerField(blank=True, null=True)),
                ('qt_litros', models.FloatField(blank=True, null=True)),
                ('qt_litros_ant', models.FloatField(blank=True, null=True)),
                ('qt_km', models.FloatField(blank=True, null=True)),
                ('qt_km_ant', models.FloatField(blank=True, null=True)),
                ('total_km', models.FloatField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField()),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_id_item', to='operacional.item')),
                ('id_veiculo', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_id_veiculo', to='operacional.veiculo')),
            ],
            options={
                'verbose_name': 'abastecimento',
                'verbose_name_plural': 'abastecimentos',
                'db_table': 'ope_abastecimento',
            },
        ),
    ]
