# Generated by Django 5.1.4 on 2025-08-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='vl_litro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['dt_abastecimento'], name='ope_abastec_dt_abas_4e991b_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['id_veiculo'], name='ope_abastec_id_veic_d8406b_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['id_item'], name='ope_abastec_id_item_cae4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['qt_litros'], name='ope_abastec_qt_litr_160d24_idx'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['total_km'], name='ope_abastec_total_k_ff3e56_idx'),
        ),
    ]
