# Generated by Django 5.1.4 on 2025-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_abastecimento_vl_litro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='vl_medio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
