# Generated by Django 5.1.4 on 2025-08-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_abastecimento_vl_medio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='vl_medio',
        ),
    ]
