# Generated by Django 5.1.4 on 2025-09-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0004_remove_abastecimento_vl_medio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimento',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'abastecimento', 'verbose_name_plural': 'abastecimentos'},
        ),
        migrations.AlterModelOptions(
            name='agregado',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'agregado', 'verbose_name_plural': 'agregados'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'serviço', 'verbose_name_plural': 'serviços'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
    ]
