# Generated by Django 5.1.4 on 2025-09-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_alter_abastecimento_options_alter_agregado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atualizações',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objeto', models.CharField(max_length=150)),
                ('dt_atualizacao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'atualização',
                'verbose_name_plural': 'atualizações',
                'db_table': 'atualizacoes',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
    ]
