# Generated by Django 5.1.4 on 2025-09-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0006_atualizações'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'categoria de lançamento',
                'verbose_name_plural': 'categorias de lançamento',
                'db_table': 'ope_categoria',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('dt_atualizacao', models.DateTimeField()),
                ('dt_criacao', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_id_usuario', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_id_veiculo', to='operacional.veiculo')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_id_categoria', to='operacional.opecategoria')),
            ],
        ),
    ]
