# Generated by Django 5.1.4 on 2025-09-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_opecategoria_lancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')], 'verbose_name': 'lancamento', 'verbose_name_plural': 'lancamentos'},
        ),
        migrations.AlterModelTable(
            name='lancamento',
            table='ope_lancamento',
        ),
    ]
