# Generated by Django 5.1.4 on 2025-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0008_alter_lancamento_options_alter_lancamento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='periodo',
            field=models.CharField(choices=[('M', 'Mensal'), ('S', 'Semanal'), ('Q', 'Quinzenal')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
