# Generated by Django 5.1.4 on 2025-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_lancamento_parcela_lancamento_periodo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordemServico', models.IntegerField(db_column='CDORDERSERVICO')),
                ('cdServico', models.IntegerField(db_column='CDSERVICO')),
                ('nmServico', models.CharField(db_column='NMSERVICO', max_length=255)),
                ('frota', models.CharField(db_column='FROTA', max_length=50)),
                ('placa', models.CharField(db_column='PLACA', max_length=20)),
                ('carreta', models.CharField(blank=True, db_column='CARRETA', max_length=20, null=True)),
                ('km', models.IntegerField(db_column='KM')),
                ('data', models.DateTimeField(db_column='DATA')),
                ('tipo', models.CharField(db_column='TIPO', max_length=50)),
                ('cdItem', models.IntegerField(db_column='CDITEM')),
                ('nmItem', models.CharField(db_column='NMITEM', max_length=255)),
                ('qtde', models.FloatField(db_column='QTDE')),
                ('unidade', models.CharField(db_column='UNIDADE', max_length=20)),
                ('valor', models.FloatField(db_column='VALOR')),
                ('total', models.FloatField(db_column='TOTAL')),
                ('periodo', models.CharField(choices=[('M', 'Mensal'), ('S', 'Semanal'), ('Q', 'Quinzenal')], default='S', max_length=10)),
                ('parcela', models.IntegerField(default=1)),
                ('dataFechamento', models.DateTimeField(db_column='DATAFECHAMENTO')),
            ],
            options={
                'verbose_name': 'fechamento',
                'verbose_name_plural': 'fechamentos',
                'db_table': 'ope_fechamento',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='periodo',
            field=models.CharField(choices=[('M', 'Mensal'), ('S', 'Semanal'), ('Q', 'Quinzenal')], default='S', max_length=10),
        ),
    ]
