# Generated by Django 5.1.4 on 2025-10-19 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0010_fechamento_alter_lancamento_periodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechamento',
            old_name='dataFechamento',
            new_name='datafechamento',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='carreta',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='cdItem',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='cdServico',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='frota',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='km',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='nmItem',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='nmServico',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='ordemServico',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='qtde',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='total',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='fechamento',
            name='cod_ag',
            field=models.CharField(blank=True, db_column='COD_AG', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fechamento',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fechamento',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fechamento',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_id_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fechamento',
            name='valor_cargas',
            field=models.FloatField(blank=True, db_column='VALOR', null=True),
        ),
        migrations.CreateModel(
            name='ItensFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordemServico', models.IntegerField(db_column='CDORDERSERVICO')),
                ('cdServico', models.IntegerField(db_column='CDSERVICO')),
                ('nmServico', models.CharField(db_column='NMSERVICO', max_length=255)),
                ('frota', models.CharField(db_column='FROTA', max_length=50)),
                ('placa', models.CharField(db_column='PLACA', max_length=20)),
                ('carreta', models.CharField(blank=True, db_column='CARRETA', max_length=20, null=True)),
                ('km', models.IntegerField(db_column='KM')),
                ('data', models.DateTimeField(db_column='DATA')),
                ('tipo', models.CharField(db_column='TIPO', max_length=50)),
                ('cdItem', models.IntegerField(db_column='CDITEM')),
                ('nmItem', models.CharField(db_column='NMITEM', max_length=255)),
                ('qtde', models.FloatField(db_column='QTDE')),
                ('unidade', models.CharField(db_column='UNIDADE', max_length=20)),
                ('valor', models.FloatField(db_column='VALOR')),
                ('total', models.FloatField(db_column='TOTAL')),
                ('periodo', models.CharField(max_length=10)),
                ('parcela', models.IntegerField()),
                ('fechamento', models.ForeignKey(db_column='id_fechamento', on_delete=django.db.models.deletion.CASCADE, related_name='itens_fechamento_id_fechamento', to='operacional.fechamento')),
            ],
            options={
                'verbose_name': 'itens de fechamento',
                'verbose_name_plural': 'itens de fechamento',
                'db_table': 'ope_itens_fechamento',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
    ]
