# Generated by Django 5.1.4 on 2025-10-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0011_rename_datafechamento_fechamento_datafechamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensfechamento',
            name='carreta',
        ),
        migrations.RemoveField(
            model_name='itensfechamento',
            name='frota',
        ),
        migrations.RemoveField(
            model_name='itensfechamento',
            name='km',
        ),
        migrations.RemoveField(
            model_name='itensfechamento',
            name='placa',
        ),
        migrations.AddField(
            model_name='fechamento',
            name='placa',
            field=models.ForeignKey(db_column='id_veiculo', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_id_veiculo', to='operacional.veiculo'),
            preserve_default=False,
        ),
    ]
