# Generated by Django 5.1.4 on 2025-10-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_itensfechamento_carreta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensfechamento',
            name='percentual',
            field=models.FloatField(db_column='PERCENTUAL', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensfechamento',
            name='valor_unitario',
            field=models.FloatField(db_column='VALOR_UNITARIO', default=1),
            preserve_default=False,
        ),
    ]
