# Generated by Django 5.1.4 on 2025-11-04 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0013_itensfechamento_percentual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechamento',
            old_name='datafechamento',
            new_name='data_fechamento',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='valor_cargas',
        ),
        migrations.AddField(
            model_name='fechamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fechamento',
            name='valor_total',
            field=models.FloatField(blank=True, db_column='VALOR_TOTAL', null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.fechamento'),
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField()),
                ('valor', models.FloatField()),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_por', models.ForeignKey(db_column='id_usuario_atualizado', on_delete=django.db.models.deletion.CASCADE, related_name='contasapagar_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(db_column='id_usuario_criado', on_delete=django.db.models.deletion.CASCADE, related_name='contasapagar_criado_por', to=settings.AUTH_USER_MODEL)),
                ('placa', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar_id_veiculo', to='operacional.veiculo')),
            ],
            options={
                'verbose_name': 'contas pagar',
                'verbose_name_plural': 'contas pagar',
                'db_table': 'ope_contas_pagar',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField()),
                ('valor', models.FloatField()),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_por', models.ForeignKey(db_column='id_usuario_atualizado', on_delete=django.db.models.deletion.CASCADE, related_name='contasareceber_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(db_column='id_usuario_criado', on_delete=django.db.models.deletion.CASCADE, related_name='contasareceber_criado_por', to=settings.AUTH_USER_MODEL)),
                ('placa', models.ForeignKey(db_column='id_veiculo', on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber_id_veiculo', to='operacional.veiculo')),
            ],
            options={
                'verbose_name': 'contas receber',
                'verbose_name_plural': 'contas receber',
                'db_table': 'ope_contas_receber',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='ItensContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=3)),
                ('codigo', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('act', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(max_length=1)),
                ('trecho', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.FloatField(default=0)),
                ('adiantamento', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('periodo', models.CharField(choices=[('M', 'Mensal'), ('S', 'Semanal'), ('Q', 'Quinzenal')], default='S', max_length=10)),
                ('parcela', models.IntegerField(default=1)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('contas_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.contaspagar')),
            ],
            options={
                'verbose_name': 'itens de contas pagar',
                'verbose_name_plural': 'itens de contas pagar',
                'db_table': 'ope_itens_contas_pagar',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='ItensContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordemServico', models.IntegerField(db_column='CDORDERSERVICO')),
                ('cdServico', models.IntegerField(db_column='CDSERVICO')),
                ('nmServico', models.CharField(db_column='NMSERVICO', max_length=255)),
                ('data', models.DateTimeField(db_column='DATA')),
                ('tipo', models.CharField(db_column='TIPO', max_length=50)),
                ('cdItem', models.IntegerField(db_column='CDITEM')),
                ('nmItem', models.CharField(db_column='NMITEM', max_length=255)),
                ('qtde', models.FloatField(db_column='QTDE')),
                ('unidade', models.CharField(db_column='UNIDADE', max_length=20)),
                ('valor_unitario', models.FloatField(db_column='VALOR_UNITARIO')),
                ('percentual', models.FloatField(db_column='PERCENTUAL')),
                ('valor', models.FloatField(db_column='VALOR')),
                ('total', models.FloatField(db_column='TOTAL')),
                ('periodo', models.CharField(max_length=10)),
                ('parcela', models.IntegerField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('contas_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.contasreceber')),
            ],
            options={
                'verbose_name': 'itens de contas receber',
                'verbose_name_plural': 'itens de contas receber',
                'db_table': 'ope_itens_contas_receber',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='VencContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_vencimento', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.FloatField()),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('contas_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.contaspagar')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.fechamento')),
            ],
            options={
                'verbose_name': 'vencimento de contas pagar',
                'verbose_name_plural': 'vencimentos de contas pagar',
                'db_table': 'ope_venc_contas_pagar',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.CreateModel(
            name='VencContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_vencimento', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.FloatField()),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('contas_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.contasreceber')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.fechamento')),
            ],
            options={
                'verbose_name': 'vencimento de contas receber',
                'verbose_name_plural': 'vencimentos de contas receber',
                'db_table': 'ope_venc_contas_receber',
                'permissions': [('acessar_operacional', 'Pode acessar o módulo de operações')],
            },
        ),
        migrations.DeleteModel(
            name='ItensFechamento',
        ),
    ]
