# Generated by Django 5.1.4 on 2025-11-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0014_rename_datafechamento_fechamento_data_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itenscontaspagar',
            table='ope_contas_pagar_itens',
        ),
        migrations.AlterModelTable(
            name='itenscontasreceber',
            table='ope_contas_receber_itens',
        ),
        migrations.AlterModelTable(
            name='venccontaspagar',
            table='ope_contas_pagar_vencimento',
        ),
        migrations.AlterModelTable(
            name='venccontasreceber',
            table='ope_contas_receber_vencimento',
        ),
    ]
