# Generated by Django 5.1.4 on 2025-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0015_alter_itenscontaspagar_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscontaspagar',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
