# Generated by Django 5.1.4 on 2025-11-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0016_alter_itenscontaspagar_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contaspagar',
            unique_together={('placa', 'data_fechamento')},
        ),
    ]
