# Generated by Django 5.1.4 on 2025-11-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0017_alter_contaspagar_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='fl_vlfixo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Valor fixo'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='valor_fixo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor fixo'),
        ),
    ]
