# Generated by Django 5.1.4 on 2025-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0018_contaspagar_fl_vlfixo_contaspagar_valor_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='natureza',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='R', max_length=10),
        ),
    ]
