# Generated by Django 5.1.4 on 2025-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0019_lancamento_natureza'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valor_fixo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
