# Generated by Django 5.1.4 on 2025-12-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0020_item_valor_fixo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valor_fixo',
        ),
    ]
