# Generated by Django 5.1.4 on 2026-02-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0021_remove_item_valor_fixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_item', models.CharField(db_index=True, max_length=50)),
                ('data', models.DateField(db_index=True)),
                ('valor', models.FloatField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'histórico de preço de item',
                'verbose_name_plural': 'históricos de preço de item',
                'db_table': 'ope_preco_hist',
                'indexes': [models.Index(fields=['cd_item', 'data'], name='ope_preco_h_cd_item_a67afc_idx')],
                'unique_together': {('cd_item', 'data')},
            },
        ),
    ]
