# Generated by Django 3.2.3 on 2021-05-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_placa', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('selecao', models.CharField(choices=[('placa', 'Placa'), ('motorista', 'Motorista'), ('todos', 'Todos')], max_length=12)),
            ],
        ),
    ]
