# Generated by Django 3.2.3 on 2021-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campos',
            name='nome_placa',
            field=models.CharField(max_length=100),
        ),
    ]
