# Generated by Django 2.1.15 on 2025-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_campos_nome_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=10, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('os', models.CharField(blank=True, max_length=30, null=True)),
                ('dtInclusao', models.CharField(blank=True, max_length=10, null=True)),
                ('userInclusao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'OrdemServico',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='campos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
