# Generated by Django 5.1.4 on 2025-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250429_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
