# Generated by Django 5.1.4 on 2025-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_campos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DummyDP',
                'permissions': [('acessar_dp', 'Pode acessar o módulo de DP')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DummyRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DummyRH',
                'permissions': [('acessar_rh', 'Pode acessar o módulo de RH')],
                'managed': False,
            },
        ),
    ]
