# Generated by Django 5.1.4 on 2025-09-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dummydp_dummyrh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummydp',
            options={'managed': False, 'permissions': [('acessar_dp', 'Pode acessar o módulo de DP'), ('acessar_rh', 'Pode acessar o módulo de RH')]},
        ),
        migrations.AlterModelOptions(
            name='dummyrh',
            options={'managed': False, 'permissions': [('acessar_dp', 'Pode acessar o módulo de DP'), ('acessar_jornada', 'Pode acessar o módulo de Jornada')]},
        ),
    ]
