# Generated by Django 5.1.4 on 2025-09-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dummydp_options_alter_dummyrh_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummydp',
            options={'managed': False, 'permissions': [('acessar_dp', 'Pode acessar o módulo de DP'), ('acessar_jornada', 'Pode acessar o módulo de Jornada')]},
        ),
        migrations.AlterModelOptions(
            name='dummyrh',
            options={'managed': False, 'permissions': [('acessar_dp', 'Pode acessar o módulo de DP')]},
        ),
    ]
