# Generated by Django 5.1.4 on 2025-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_dummydp_options_alter_dummyrh_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPermissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DummyDP',
                'permissions': [('acessar_dp', 'Pode acessar o módulo de DP'), ('acessar_rh', 'Pode acessar o módulo de RH'), ('acessar_jornada', 'Pode acessar o módulo de Jornada')],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DummyDP',
        ),
        migrations.DeleteModel(
            name='DummyRH',
        ),
    ]
