# Generated by Django 2.1.15 on 2025-04-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
            options={
                'db_table': 'Acesso',
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=40)),
                ('link', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Link',
            },
        ),
        migrations.AddField(
            model_name='acesso',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.Link'),
        ),
    ]
